### ISSUE TITLE
Container Job Compatibility

### ISSUE THREAD

**Issue by sjqnn** [Fizcko/Azure_DevOps_Vault_Interaction#15]
Is there a proven way/ is there some requirement to be installed in an image running this task to allow for it to be run in the context of a container job?

I tried using this task in a container, and it consistently came back with the following error. As soon as I switched it to just run on a bare rhel VM agent it worked fine. 

``` 
(node:103) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'data' of undefined 
```

**Comment by Fizcko** [comment]
I dont thinks that there is some requirements.
Can you publish your YAML pipeline job ?

**Comment by Fizcko** [comment]
Thanks i will try to reproduce the error.

**Comment by Fizcko** [comment]
@sjqnn i'm not able to reproduce the same error. Is it possible to get more logs even censured ? You can run the task in debug mode like this
```yaml
stages:
  - stage: GetSecret
    displayName: "Get Secret"
    jobs:
      - job: GetSecret
        variables:
          - name: System.Debug
            value: true
        container: python:3.8-slim-buster
...
```
